version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: myapp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - mongodb_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_web
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8082:8081"
    networks:
      - mongodb_network
    depends_on:
      - mongodb

volumes:
  mongodb_data:

networks:
  mongodb_network:
    driver: bridge
