version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_server
    restart: unless-stopped
    user: root
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8083:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - docker_certs:/certs/client:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network

  docker:
    image: docker:dind
    container_name: jenkins_docker
    restart: unless-stopped
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins_home:/var/jenkins_home
      - docker_certs:/certs/client
      - docker_data:/var/lib/docker
    ports:
      - "2376:2376"
    networks:
      - jenkins_network
    command: --storage-driver=overlay2

volumes:
  jenkins_home:
  docker_certs:
  docker_data:

networks:
  jenkins_network:
    driver: bridge
